---
server_group:
  data:
    - host:
        ip: "127.0.0.1"
        port: 30002
      naming:
        service_name: "test_service"
      customize:
        env_type: "debug"
        worker_count: 10
    - host:
        ip: "127.0.0.1"
        port: 30003
      naming:
        service_name: "test_service2"
      customize:
        env_type: "debug"
        worker_count: 10
redis_conf:
  data:
    - host:
        ip: "127.0.0.1"
        port: 6379
      db_no: 0
    - host:
        ip: "127.0.0.1"
        port: 6379
      db_no: 1
    - host:
        ip: "127.0.0.1"
        port: 6379
      db_no: 2
    - host:
        ip: "127.0.0.1"
        port: 6379
      db_no: 3
