---
server_group:
  -
    host:
      ip: "127.0.0.1"
      port: 30002
    naming:
      service_name: "test_service"
    customize:
      env_type: "debug"
      worker_count: 10
  -
    host:
      ip: "127.0.0.1"
      port: 30003
    naming:
      service_name: "test_service2"
    customize:
      env_type: "debug"
      worker_count: 10