---
server_group:
  data:
    - host:
        ip: "127.0.0.1"
        port: 30002
      naming:
        service_name: "test_service"
      customize:
        env_type: "debug"
        worker_count: 10
    # - host:
    #     ip: "127.0.0.1"
    #     port: 30003
    #   naming:
    #     service_name: "test_service2"
    #   customize:
    #     env_type: "debug"
    #     worker_count: 10
mq_conf:
  mem_channel_bound: 16
  buffered_writes_high_water: 16777216
  buffered_writes_low_water: 0
  user: "admin"
  password: "admin"
  host:
    ip: "127.0.0.1"
    port: 5672
  publish_exchange:
    direct: "game_server.direct"
    fanout: "game_server.fanout"
redis_conf:
  data:
    - host:
        ip: "127.0.0.1"
        port: 6379
      db_no: 0
    - host:
        ip: "127.0.0.1"
        port: 6379
      db_no: 1
    - host:
        ip: "127.0.0.1"
        port: 6379
      db_no: 2
    - host:
        ip: "127.0.0.1"
        port: 6379
      db_no: 3
