[package]
name = "ex_util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ex_common = { path = "../ex_common" }

ctrlc = "3.2.3"
spin="0.9.4"